#if !canImport(ObjectiveC)
import XCTest

extension HttpCookieCodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HttpCookieCodableTests = [
        ("testRoundTrip", testRoundTrip),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HttpCookieCodableTests.__allTests__HttpCookieCodableTests),
    ]
}
#endif
